/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BookmarkCreatorPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  bookmarkFolder: "Bookmarks",
  attachmentFolder: "assets/images",
  jinaApiKey: "",
  aiApiBaseUrl: "https://api.openai.com/v1",
  aiApiModel: "gpt-3.5-turbo",
  aiApiKey: "",
  aiPromptTemplate: `\u8BF7\u6839\u636E\u63D0\u4F9B\u7684\u7F51\u9875\u5185\u5BB9\u548C\u641C\u7D22\u4FE1\u606F\uFF0C\u751F\u6210\u5B8C\u6574\u7684\u4E66\u7B7EYAML\u4FE1\u606F\u3002\u6211\u4F1A\u63D0\u4F9B\u76EE\u6807\u7F51\u5740\u3001\u7F51\u9875\u5185\u5BB9\u6458\u8981\u4EE5\u53CA\u76F8\u5173\u641C\u7D22\u8BC4\u4EF7\uFF0C\u4F60\u9700\u8981\u751F\u6210\u7B26\u5408Obsidian\u4E66\u7B7E\u683C\u5F0F\u7684YAML\u6570\u636E\u3002

## \u751F\u6210\u8981\u6C42\uFF1A

### \u6807\u9898\u89C4\u8303
- \u4F7F\u7528\u7B80\u6D01\u7684\u7F51\u7AD9\u540D\u79F0\uFF0C\u4E0D\u5305\u542B\u63CF\u8FF0\u6027\u6587\u5B57
- \u53BB\u9664\u5197\u4F59\u7684\u516C\u53F8\u3001\u5B98\u7F51\u7B49\u5B57\u6837
- \u4FDD\u6301\u539F\u59CB\u54C1\u724C\u540D\u79F0\uFF0C\u4E0D\u8981\u7FFB\u8BD1\u4E13\u6709\u540D\u8BCD

### \u63CF\u8FF0\u89C4\u8303  
- \u8BF4\u660E\u7F51\u7AD9\u7684\u6838\u5FC3\u529F\u80FD\u548C\u4EF7\u503C
- \u7A81\u51FA\u7F51\u7AD9\u7684\u4E3B\u8981\u7528\u9014\u548C\u7279\u8272
- \u4F7F\u7528\u7B80\u4F53\u4E2D\u6587\uFF0C\u907F\u514D\u5197\u957F\u4ECB\u7ECD
- \u63CF\u8FF0\u8981\u5177\u4F53\u6709\u7528\uFF0C\u907F\u514D\u7A7A\u6CDB\u7684\u5F62\u5BB9\u8BCD
- \u4E0D\u8D85\u8FC7 300 \u5B57

### \u6807\u7B7E\u89C4\u8303
1. **\u4E3B\u8981\u5206\u7C7B\u6807\u7B7E**\uFF081-2\u4E2A\uFF09\uFF1A
   - \u4ECE\u9884\u8BBE\u5206\u7C7B\u4E2D\u9009\u62E9\u6700\u5408\u9002\u7684\u5206\u7C7B
   - \u683C\u5F0F\uFF1A\u4E00\u7EA7\u5206\u7C7B/\u4E8C\u7EA7\u5206\u7C7B
   - \u4F18\u5148\u9009\u62E9\u6700\u8D34\u5207\u7684\u5355\u4E00\u5206\u7C7B

2. **\u529F\u80FD\u6807\u7B7E**\uFF082-4\u4E2A\uFF09\uFF1A
   - \u63CF\u8FF0\u7F51\u7AD9\u7684\u6838\u5FC3\u529F\u80FD\u6216\u7279\u70B9
   - \u4F7F\u7528\u7B80\u6D01\u7684\u4E2D\u6587\u8BCD\u6C47
   - \u907F\u514D\u8FC7\u4E8E\u5BBD\u6CDB\u7684\u6807\u7B7E

3. **\u7279\u8272\u6807\u7B7E**\uFF081-2\u4E2A\uFF09\uFF1A
   - \u7A81\u51FA\u7F51\u7AD9\u7684\u72EC\u7279\u4E4B\u5904
   - \u53EF\u4EE5\u662F\u6280\u672F\u7279\u70B9\u3001\u7528\u6237\u7FA4\u4F53\u3001\u5185\u5BB9\u7C7B\u578B\u7B49

\u603B\u6807\u7B7E\u6570\u91CF\u63A7\u5236\u57284-7\u4E2A\uFF0C\u786E\u4FDD\u6BCF\u4E2A\u6807\u7B7E\u90FD\u6709\u5B9E\u9645\u610F\u4E49\u3002

## \u8F93\u51FA\u683C\u5F0F\uFF1A

\u4E25\u683C\u6309\u7167\u4EE5\u4E0BYAML\u683C\u5F0F\u8F93\u51FA\uFF0C\u6807\u7B7E\u4F7F\u7528\u5217\u8868\u683C\u5F0F\uFF1A

\`\`\`yaml
---
created: 
title: \u7F51\u7AD9\u6807\u9898
url: \u76EE\u6807\u7F51\u5740
description: \u7F51\u7AD9\u529F\u80FD\u63CF\u8FF0
tags: 
    - \u5206\u7C7B\u6807\u7B7E
    - \u529F\u80FD\u6807\u7B7E1
    - \u529F\u80FD\u6807\u7B7E2
    - \u7279\u8272\u6807\u7B7E
---
\`\`\`

## \u9884\u8BBE\u5206\u7C7B\uFF1A

- \u5DE5\u4F5C\u5B66\u4E60\uFF1A\u529E\u516C\u8F6F\u4EF6\u3001\u5F00\u53D1\u5DE5\u5177\u3001\u8BBE\u8BA1\u8D44\u6E90\u3001\u5B66\u4E60\u5E73\u53F0\u3001\u6587\u6863\u8D44\u6599
- \u5B9E\u7528\u5DE5\u5177\uFF1A\u641C\u7D22\u5F15\u64CE\u3001\u7FFB\u8BD1\u5DE5\u5177\u3001\u6587\u4EF6\u5904\u7406\u3001\u7CFB\u7EDF\u5DE5\u5177\u3001\u5B89\u5168\u9690\u79C1  
- \u79D1\u6280\u6570\u7801\uFF1A\u4EA7\u54C1\u8D44\u8BAF\u3001\u8F6F\u4EF6\u4E0B\u8F7D\u3001\u786C\u4EF6\u4FE1\u606F\u3001\u6559\u7A0B\u653B\u7565
- \u8D2D\u7269\u6D88\u8D39\uFF1A\u7535\u5546\u5E73\u53F0\u3001\u6BD4\u4EF7\u5DE5\u5177\u3001\u652F\u4ED8\u670D\u52A1\u3001\u8D2D\u7269\u653B\u7565
- \u5A31\u4E50\u5F71\u97F3\uFF1A\u89C6\u9891\u7F51\u7AD9\u3001\u97F3\u4E50\u5E73\u53F0\u3001\u6E38\u620F\u5A31\u4E50\u3001\u9605\u8BFB\u5C0F\u8BF4
- \u65B0\u95FB\u8D44\u8BAF\uFF1A\u7EFC\u5408\u65B0\u95FB\u3001\u884C\u4E1A\u8D44\u8BAF\u3001\u672C\u5730\u4FE1\u606F
- \u751F\u6D3B\u4F11\u95F2\uFF1A\u65C5\u6E38\u51FA\u884C\u3001\u7F8E\u98DF\u70F9\u996A\u3001\u5065\u5EB7\u517B\u751F\u3001\u5BB6\u5C45\u751F\u6D3B
- \u793E\u4EA4\u793E\u533A\uFF1A\u793E\u4EA4\u5E73\u53F0\u3001\u8BBA\u575B\u793E\u533A\u3001\u535A\u5BA2\u5E73\u53F0
- \u6295\u8D44\u7406\u8D22\uFF1A\u80A1\u7968\u57FA\u91D1\u3001\u8D22\u7ECF\u8D44\u8BAF\u3001\u7406\u8D22\u5DE5\u5177
- \u7BA1\u7406\u7EF4\u62A4\uFF1A\u5F85\u5904\u7406\u3001\u91CD\u8981\u5907\u4EFD\u3001\u5386\u53F2\u5B58\u6863\u3001\u6D4B\u8BD5\u5F00\u53D1

## \u6CE8\u610F\u4E8B\u9879\uFF1A

- \u4FDD\u6301YAML\u8BED\u6CD5\u6B63\u786E\uFF0C\u4F7F\u7528\u591A\u884C\u6807\u7B7E\u683C\u5F0F
- \u6807\u7B7E\u4F18\u5148\u4F7F\u7528\u7B80\u4F53\u4E2D\u6587\uFF0C\u5982\u975E\u5FC5\u8981\u7684\u4E13\u4E1A\u540D\u8BCD\u907F\u514D\u82F1\u6587\u6807\u7B7E
- \u4E0D\u8981\u6DFB\u52A0\u5F15\u53F7\uFF0C\u9664\u975E\u5FC5\u8981
- \u786E\u4FDD\u751F\u6210\u7684\u4FE1\u606F\u51C6\u786E\u53CD\u6620\u7F51\u7AD9\u5B9E\u9645\u5185\u5BB9`
};
var BookmarkCreatorSettingTab = class extends import_obsidian.PluginSettingTab {
  /**
   * 构造函数
   * @param app - Obsidian应用实例
   * @param plugin - 书签创建器插件实例
   */
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  /**
   * 显示设置页面
   * 渲染所有设置选项和说明
   * 
   * @returns {void}
   */
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u4E66\u7B7E\u521B\u5EFA\u5668\u8BBE\u7F6E" });
    containerEl.createEl("h3", { text: "\u57FA\u7840\u8BBE\u7F6E" });
    this.createBookmarkFolderSetting(containerEl);
    this.createAttachmentFolderSetting(containerEl);
    containerEl.createEl("h3", { text: "Jina AI API\u8BBE\u7F6E" });
    this.createJinaApiKeySetting(containerEl);
    containerEl.createEl("h3", { text: "AI\u5904\u7406API\u8BBE\u7F6E" });
    this.createAiApiBaseUrlSetting(containerEl);
    this.createAiApiModelSetting(containerEl);
    this.createAiApiKeySetting(containerEl);
    this.createAiPromptTemplateSetting(containerEl);
    this.createUsageInstructions(containerEl);
  }
  /**
   * 创建书签文件夹设置
   * @private
   * @param {HTMLElement} containerEl - 容器元素
   * @returns {void}
   */
  createBookmarkFolderSetting(containerEl) {
    new import_obsidian.Setting(containerEl).setName("\u4E66\u7B7E\u6587\u4EF6\u5939").setDesc("\u5B58\u50A8\u4E66\u7B7E\u7B14\u8BB0\u7684\u6587\u4EF6\u5939\u8DEF\u5F84").addText((text) => text.setPlaceholder("Bookmarks").setValue(this.plugin.settings.bookmarkFolder).onChange(async (value) => {
      this.plugin.settings.bookmarkFolder = value.trim() || "Bookmarks";
      await this.plugin.saveSettings();
    }));
  }
  /**
   * 创建附件文件夹设置
   * @private
   * @param {HTMLElement} containerEl - 容器元素
   * @returns {void}
   */
  createAttachmentFolderSetting(containerEl) {
    new import_obsidian.Setting(containerEl).setName("\u9644\u4EF6\u6587\u4EF6\u5939").setDesc("\u5B58\u50A8\u622A\u56FE\u7684\u6587\u4EF6\u5939\u8DEF\u5F84").addText((text) => text.setPlaceholder("Attachments").setValue(this.plugin.settings.attachmentFolder).onChange(async (value) => {
      this.plugin.settings.attachmentFolder = value.trim() || "Attachments";
      await this.plugin.saveSettings();
    }));
  }
  /**
   * 创建使用说明
   * @private
   * @param {HTMLElement} containerEl - 容器元素
   * @returns {void}
   */
  createUsageInstructions(containerEl) {
    containerEl.createEl("h3", { text: "\u4F7F\u7528\u8BF4\u660E" });
    const instructions = [
      '1. \u4F7F\u7528\u547D\u4EE4\u9762\u677F (Ctrl/Cmd + P) \u8F93\u5165 "\u521B\u5EFA\u4E66\u7B7E\u7B14\u8BB0" \u6765\u542F\u52A8\u63D2\u4EF6',
      "2. \u652F\u6301\u4E24\u79CD\u8F93\u5165\u65B9\u5F0F\uFF1A",
      "   - YAML\u683C\u5F0F\uFF1A\u6309\u4F20\u7EDF\u65B9\u5F0F\u8F93\u5165\u5B8C\u6574\u7684\u4E66\u7B7E\u4FE1\u606F",
      "   - \u76F4\u63A5\u8F93\u5165\u7F51\u5740\uFF1A\u63D2\u4EF6\u5C06\u4F7F\u7528AI\u81EA\u52A8\u751F\u6210\u4E66\u7B7E\u4FE1\u606F",
      "3. \u63D2\u4EF6\u4F1A\u81EA\u52A8\u8865\u5168\u521B\u5EFA\u65F6\u95F4\u3001\u751F\u6210\u7F51\u7AD9\u622A\u56FE\u5E76\u521B\u5EFA\u7B14\u8BB0",
      "4. \u622A\u56FE\u53EF\u80FD\u9700\u8981\u51E0\u79D2\u949F\u65F6\u95F4\u751F\u6210\uFF0C\u8BF7\u8010\u5FC3\u7B49\u5F85"
    ];
    instructions.forEach((instruction) => {
      containerEl.createEl("p", { text: instruction });
    });
    this.createYamlExample(containerEl);
    this.createAiFeatureInstructions(containerEl);
  }
  /**
   * 创建AI功能使用说明
   * @private
   * @param {HTMLElement} containerEl - 容器元素
   * @returns {void}
   */
  createAiFeatureInstructions(containerEl) {
    containerEl.createEl("h4", { text: "AI\u81EA\u52A8\u751F\u6210\u529F\u80FD\uFF1A" });
    const aiInstructions = [
      "\u2022 \u76F4\u63A5\u8F93\u5165\u7F51\u5740\uFF08\u5982\uFF1Ahttps://example.com/\uFF09",
      "\u2022 \u63D2\u4EF6\u4F1A\u81EA\u52A8\uFF1A",
      "  - \u4F7F\u7528Jina AI\u63D0\u53D6\u7F51\u9875\u5185\u5BB9",
      "  - \u641C\u7D22\u76F8\u5173\u4FE1\u606F\u548C\u8BC4\u4EF7",
      "  - \u4F7F\u7528AI\u751F\u6210\u5B8C\u6574\u7684\u4E66\u7B7EYAML\u4FE1\u606F",
      "\u2022 \u9700\u8981\u914D\u7F6EJina AI API\u5BC6\u94A5\u548CAI API\u5BC6\u94A5",
      "\u2022 \u751F\u6210\u7684\u4E66\u7B7E\u5305\u542B\u6807\u9898\u3001\u63CF\u8FF0\u548C\u5408\u9002\u7684\u6807\u7B7E"
    ];
    aiInstructions.forEach((instruction) => {
      containerEl.createEl("p", { text: instruction });
    });
  }
  /**
   * 创建Jina API密钥设置
   * @private
   * @param {HTMLElement} containerEl - 容器元素
   * @returns {void}
   */
  createJinaApiKeySetting(containerEl) {
    new import_obsidian.Setting(containerEl).setName("Jina AI API\u5BC6\u94A5").setDesc("\u7528\u4E8E\u63D0\u53D6\u7F51\u9875\u5185\u5BB9\u7684Jina AI API\u5BC6\u94A5\uFF08\u53EF\u9009\uFF09").addText((text) => text.setPlaceholder("\u8F93\u5165Jina AI API\u5BC6\u94A5").setValue(this.plugin.settings.jinaApiKey).onChange(async (value) => {
      this.plugin.settings.jinaApiKey = value.trim();
      await this.plugin.saveSettings();
    }));
  }
  /**
   * 创建AI API基础URL设置
   * @private
   * @param {HTMLElement} containerEl - 容器元素
   * @returns {void}
   */
  createAiApiBaseUrlSetting(containerEl) {
    new import_obsidian.Setting(containerEl).setName("AI API\u57FA\u7840URL").setDesc("AI\u5904\u7406API\u7684\u57FA\u7840URL\uFF0C\u9ED8\u8BA4\u4E3AOpenAI\u683C\u5F0F").addText((text) => text.setPlaceholder("https://api.openai.com/v1").setValue(this.plugin.settings.aiApiBaseUrl).onChange(async (value) => {
      this.plugin.settings.aiApiBaseUrl = value.trim() || "https://api.openai.com/v1";
      await this.plugin.saveSettings();
    }));
  }
  /**
   * 创建AI API模型设置
   * @private
   * @param {HTMLElement} containerEl - 容器元素
   * @returns {void}
   */
  createAiApiModelSetting(containerEl) {
    new import_obsidian.Setting(containerEl).setName("AI API\u6A21\u578B").setDesc("\u7528\u4E8E\u5904\u7406\u4E66\u7B7E\u4FE1\u606F\u7684AI\u6A21\u578B\u540D\u79F0").addText((text) => text.setPlaceholder("gpt-3.5-turbo").setValue(this.plugin.settings.aiApiModel).onChange(async (value) => {
      this.plugin.settings.aiApiModel = value.trim() || "gpt-3.5-turbo";
      await this.plugin.saveSettings();
    }));
  }
  /**
   * 创建AI API密钥设置
   * @private
   * @param {HTMLElement} containerEl - 容器元素
   * @returns {void}
   */
  createAiApiKeySetting(containerEl) {
    new import_obsidian.Setting(containerEl).setName("AI API\u5BC6\u94A5").setDesc("\u7528\u4E8E\u5904\u7406\u4E66\u7B7E\u4FE1\u606F\u7684AI API\u5BC6\u94A5").addText((text) => text.setPlaceholder("\u8F93\u5165AI API\u5BC6\u94A5").setValue(this.plugin.settings.aiApiKey).onChange(async (value) => {
      this.plugin.settings.aiApiKey = value.trim();
      await this.plugin.saveSettings();
    }));
  }
  /**
   * 创建AI提示词模板设置
   * @private
   * @param {HTMLElement} containerEl - 容器元素
   * @returns {void}
   */
  createAiPromptTemplateSetting(containerEl) {
    new import_obsidian.Setting(containerEl).setName("AI\u63D0\u793A\u8BCD\u6A21\u677F").setDesc("\u7528\u4E8E\u751F\u6210\u4E66\u7B7E\u4FE1\u606F\u7684AI\u63D0\u793A\u8BCD\u6A21\u677F").addTextArea((text) => {
      text.setPlaceholder("\u8F93\u5165AI\u63D0\u793A\u8BCD\u6A21\u677F").setValue(this.plugin.settings.aiPromptTemplate).onChange(async (value) => {
        this.plugin.settings.aiPromptTemplate = value.trim() || DEFAULT_SETTINGS.aiPromptTemplate;
        await this.plugin.saveSettings();
      });
      text.inputEl.rows = 10;
      text.inputEl.style.fontFamily = "monospace";
      text.inputEl.style.fontSize = "12px";
      text.inputEl.style.width = "100%";
    });
  }
  /**
   * 创建YAML格式示例
   * @private
   * @param {HTMLElement} containerEl - 容器元素
   * @returns {void}
   */
  createYamlExample(containerEl) {
    containerEl.createEl("h4", { text: "YAML\u683C\u5F0F\u793A\u4F8B\uFF1A" });
    const exampleCode = containerEl.createEl("pre", {
      text: `---
created: 
title: \u5C0F\u4F17\u8F6F\u4EF6
url: https://www.appinn.com/
description: \u4E13\u6CE8\u5206\u4EAB\u514D\u8D39\u3001\u5C0F\u5DE7\u3001\u5B9E\u7528\u3001\u6709\u8DA3\u3001\u7EFF\u8272\u8F6F\u4EF6\u4E0E\u5E94\u7528\u7684\u56E2\u961F\u535A\u5BA2
tags: 
    - \u79D1\u6280\u6570\u7801/\u8F6F\u4EF6\u4E0B\u8F7D
    - \u5B9E\u7528\u5DE5\u5177
    - \u8F6F\u4EF6\u8BC4\u6D4B
---`,
      cls: "yaml-example"
    });
    exampleCode.style.backgroundColor = "#f5f5f5";
    exampleCode.style.padding = "10px";
    exampleCode.style.borderRadius = "4px";
    exampleCode.style.fontFamily = "monospace";
    exampleCode.style.fontSize = "14px";
    exampleCode.style.overflowX = "auto";
  }
};

// src/modal.ts
var import_obsidian5 = require("obsidian");

// src/steps.ts
var allSteps = [
  {
    "title": "\u83B7\u53D6\u7F51\u9875\u5185\u5BB9",
    "desc": "\u4F7F\u7528 Jina \u4ECE\u76EE\u6807\u7F51\u5740\u83B7\u53D6\u5185\u5BB9",
    "name": "get-web-content",
    "estimatedTime": 30
  },
  {
    "title": "\u83B7\u53D6\u7F51\u7AD9\u8BC4\u4EF7",
    "desc": "\u4F7F\u7528 Jina \u641C\u7D22\u76EE\u6807\u7F51\u5740\u83B7\u53D6\u76F8\u5173\u8BC4\u4EF7",
    "name": "get-web-rating",
    "estimatedTime": 60
  },
  {
    "title": "\u751F\u6210\u4E66\u7B7E\u4FE1\u606F",
    "desc": "\u4F7F\u7528 AI \u6839\u636E\u83B7\u53D6\u7684\u5185\u5BB9\u751F\u6210\u4E66\u7B7E\u4FE1\u606F",
    "name": "generate-bookmark-info",
    "estimatedTime": 60
  },
  {
    "title": "\u4E0B\u8F7D\u7F51\u7AD9\u622A\u56FE",
    "desc": "\u4F7F\u7528 Thum.io \u4E0B\u8F7D\u76EE\u6807\u7F51\u5740\u7684\u622A\u56FE",
    "name": "download-web-screenshot",
    "estimatedTime": 60
  },
  {
    "title": "\u521B\u5EFA\u4E66\u7B7E\u7B14\u8BB0",
    "desc": "\u6839\u636E\u751F\u6210\u7684\u4E66\u7B7E\u4FE1\u606F\u521B\u5EFA Obsidian \u7B14\u8BB0",
    "name": "create-bookmark-note",
    "estimatedTime": 10
  }
];
var steps = {
  "full": allSteps,
  "simple": allSteps.slice(3)
};

// src/waitlist.ts
var WaitlistManager = class {
  constructor() {
    /** 等待队列数组 */
    this.waitlist = [];
    /** 事件监听器映射 */
    this.listeners = /* @__PURE__ */ new Map();
  }
  /**
   * 向等待队列中添加新项
   * @param url - 网址
   * @param type - 处理类型，默认为 'full'
   */
  add(url, type = "full") {
    const status = {};
    if (type === "full") {
      steps.full.forEach((step) => {
        status[step.name] = { step: step.name, status: "pending" };
      });
    } else {
      steps.simple.forEach((step) => {
        status[step.name] = { step: step.name, status: "pending" };
      });
    }
    const item = { url, status };
    this.waitlist.push(item);
    this.emit("add", { url, type, item, count: this.waitlist.length });
    return this.waitlist.length;
  }
  /**
   * 读取队列中的第n个元素
   * @param n - 元素索引，默认为 0
   * @returns 第n个元素，如果索引超出范围则返回 null
   */
  read(n = 0) {
    const item = this.waitlist[n] || null;
    this.emit("read", { item, count: this.waitlist.length, index: n });
    return item;
  }
  /**
   * 删除队列中的第一个元素
   * @returns 被删除的元素，如果队列为空则返回 null
   */
  remove() {
    const item = this.waitlist.shift() || null;
    if (item) {
      this.emit("remove", { item, count: this.waitlist.length });
    }
    return item;
  }
  /**
   * 清空等待队列
   */
  clear() {
    this.waitlist = [];
    this.emit("clear", { count: 0 });
  }
  /**
   * 更新队列中第n个元素的状态
   * @param step - 要更新的步骤名称
   * @param status - 新的状态值
   * @param n - 元素索引，默认为 0
   */
  update(step, status, n = 0) {
    const item = this.waitlist[n];
    if (item && item.status[step]) {
      const oldStatus = item.status[step].status;
      item.status[step].status = status;
      this.emit("update", { url: item.url, step, oldStatus, newStatus: status, index: n, count: this.waitlist.length });
    }
  }
  /**
   * 订阅事件
   * @param event - 事件类型
   * @param listener - 事件监听器
   */
  subscribe(event, listener) {
    if (!this.listeners.has(event)) {
      this.listeners.set(event, /* @__PURE__ */ new Set());
    }
    this.listeners.get(event).add(listener);
  }
  /**
   * 取消订阅事件
   * @param event - 事件类型
   * @param listener - 事件监听器
   */
  unsubscribe(event, listener) {
    const listeners = this.listeners.get(event);
    if (listeners) {
      listeners.delete(listener);
    }
  }
  /**
   * 触发事件
   * @param event - 事件类型
   * @param data - 事件数据
   */
  emit(event, data) {
    const listeners = this.listeners.get(event);
    if (listeners) {
      listeners.forEach((listener) => listener(data));
    }
  }
  /**
   * 获取当前队列长度
   */
  get length() {
    return this.waitlist.length;
  }
  /**
   * 获取队列副本（防止外部修改）
   */
  get items() {
    return [...this.waitlist];
  }
};
var waitlist = new WaitlistManager();

// src/workflow.ts
var import_obsidian4 = require("obsidian");

// src/types.ts
var WorkflowCancellationError = class extends Error {
  constructor(message = "\u5DE5\u4F5C\u6D41\u5DF2\u53D6\u6D88") {
    super(message);
    this.name = "WorkflowCancellationError";
  }
};

// src/ApiCaller.ts
var import_obsidian2 = require("obsidian");
var AiService = class {
  /**
   * 构造函数
   * @param {BookmarkCreatorSettings} settings - 插件设置
   */
  constructor(settings) {
    this.settings = settings;
  }
  /**
   * 调用AI API
   * @param {string} url - 要处理的URL
   * @param {AiServiceType} type - 服务类型（jinaReader、jinaSearch或openai）
   * @param {siteInfoObj} [siteInfo] - 可选的站点信息对象，用于openai服务
   * @returns {Promise<string>} 处理后的内容或错误消息
   * @throws {Error} 当服务类型无效、API密钥未设置、URL格式错误或API调用失败时抛出错误
   */
  async callApi(url, type, siteInfo) {
    var _a, _b, _c, _d, _e;
    if (type === "jinaReader" || type === "jinaSearch") {
      if (!this.settings.jinaApiKey) {
        throw new Error("Jina AI API\u5BC6\u94A5\u672A\u8BBE\u7F6E");
      }
      try {
        new URL(url);
      } catch (e) {
        throw new Error("\u65E0\u6548\u7684\u7F51\u5740\u683C\u5F0F");
      }
    } else if (type === "openai") {
      if (!this.settings.aiApiKey) {
        throw new Error("AI API\u5BC6\u94A5\u672A\u8BBE\u7F6E");
      }
      try {
        new URL(this.settings.aiApiBaseUrl);
      } catch (e) {
        throw new Error("AI API\u57FA\u7840URL\u683C\u5F0F\u65E0\u6548");
      }
    } else {
      throw new Error(`\u672A\u77E5\u7684AI\u670D\u52A1\u7C7B\u578B: ${type}`);
    }
    const typeNames = {
      "jinaReader": "Jina AI \u8BFB\u53D6\u5668",
      "jinaSearch": "Jina AI \u641C\u7D22\u5668",
      "openai": "AI \u5904\u7406\u5668"
    };
    const serviceName = typeNames[type];
    let response;
    try {
      if (type === "jinaReader") {
        response = await (0, import_obsidian2.requestUrl)({
          url: `https://r.jina.ai/${encodeURIComponent(url)}`,
          method: "GET",
          headers: {
            "Authorization": `Bearer ${this.settings.jinaApiKey}`,
            "Accept": "application/json",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
          }
        });
      } else if (type === "jinaSearch") {
        const domain = new URL(url).hostname;
        response = await (0, import_obsidian2.requestUrl)({
          url: `https://s.jina.ai/${encodeURIComponent(domain)}`,
          method: "GET",
          headers: {
            "Authorization": `Bearer ${this.settings.jinaApiKey}`,
            "Accept": "application/json",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
          }
        });
      } else if (type === "openai") {
        response = await this.generateBookmarkYaml(url, siteInfo.webContent, siteInfo.searchInfo);
      }
      if (response.status === 200) {
        const data = JSON.parse(response.text);
        const content = (type === "openai" ? (_c = (_b = (_a = data.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content : ((_d = data.data) == null ? void 0 : _d.content) || ((_e = data == null ? void 0 : data.data) == null ? void 0 : _e.toString()) || data.content) || "";
        if (!content || content.trim().length === 0) {
          console.log(`${serviceName}: API\u8FD4\u56DE\u5185\u5BB9\u4E3A\u7A7A:`, data);
        }
        return content;
      } else if (response.status === 401) {
        throw new Error(`${serviceName}: API\u5BC6\u94A5\u65E0\u6548\u6216\u5DF2\u8FC7\u671F`);
      } else if (response.status === 429) {
        throw new Error(`${serviceName}: API\u8BF7\u6C42\u8FC7\u4E8E\u9891\u7E41\uFF0C\u8BF7\u7A0D\u540E\u518D\u8BD5`);
      } else if (response.status >= 500) {
        throw new Error(`${serviceName}: \u670D\u52A1\u6682\u65F6\u4E0D\u53EF\u7528\uFF0C\u8BF7\u7A0D\u540E\u518D\u8BD5`);
      } else {
        throw new Error(`${serviceName}: API\u8FD4\u56DE\u9519\u8BEF\uFF0C\u72B6\u6001\u7801: ${response.status}`);
      }
    } catch (error) {
      console.error(`${serviceName}: \u8C03\u7528API\u65F6\u53D1\u751F\u9519\u8BEF:`, error);
      if (error instanceof Error) {
        throw new Error(`AI\u4E66\u7B7E\u751F\u6210\u5931\u8D25: ${error.message}`);
      } else {
        throw new Error("AI\u4E66\u7B7E\u751F\u6210\u5931\u8D25: \u672A\u77E5\u9519\u8BEF");
      }
    }
  }
  /**
   * 使用AI生成书签YAML信息
   * @param {string} url - 网页URL
   * @param {string} webContent - 网页内容
   * @param {string} searchInfo - 搜索信息
   * @returns {Promise<string>} 生成的YAML内容
   * @throws {Error} 当API调用失败或生成内容无效时抛出错误
   */
  async generateBookmarkYaml(url, webContent, searchInfo) {
    const truncatedWebContent = webContent.length > 2e3 ? webContent.substring(0, 2e3) + "..." : webContent;
    const truncatedSearchInfo = searchInfo.length > 8e3 ? searchInfo.substring(0, 8e3) + "..." : searchInfo;
    const prompt = `${this.settings.aiPromptTemplate}

## \u7F51\u9875\u5185\u5BB9\uFF1A
${truncatedWebContent}

## \u641C\u7D22\u4FE1\u606F\uFF1A
${truncatedSearchInfo}

## \u76EE\u6807\u7F51\u5740\uFF1A
${url}
`;
    const response = await (0, import_obsidian2.requestUrl)({
      url: `${this.settings.aiApiBaseUrl}/chat/completions`,
      method: "POST",
      headers: {
        "Authorization": `Bearer ${this.settings.aiApiKey}`,
        "Content-Type": "application/json",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
      },
      body: JSON.stringify({
        model: this.settings.aiApiModel,
        messages: [
          {
            role: "user",
            content: prompt
          }
        ],
        temperature: 0.3,
        // 降低温度以获得更稳定的输出
        max_tokens: 1500,
        // 减少最大token数以避免过长的响应
        top_p: 0.9
      })
    });
    return response;
  }
};

// src/FileManager.ts
var import_obsidian3 = require("obsidian");
var FileManager = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  /**
   * 确保文件夹存在
   * @param folderPath - 文件夹路径
   * @returns 是否创建了新文件夹
   */
  async ensureFolderExists(folderPath) {
    const isExist = await this.app.vault.adapter.exists(folderPath);
    try {
      if (!isExist) {
        await this.app.vault.createFolder(folderPath);
        return true;
      } else {
        return false;
      }
    } catch (error) {
      new import_obsidian3.Notice(`\u521B\u5EFA\u6587\u4EF6\u5939 ${folderPath} \u5931\u8D25`);
      return false;
    }
  }
  /**
  * 清理文件名，移除非法字符
  * 
  * @param {string} fileName - 原始文件名
  * @returns {string} 清理后的文件名
  */
  sanitizeFileName(fileName) {
    return fileName.replace(/[<>:\"/\\|?*]/g, "_").replace(/\s+/g, " ").trim();
  }
  /**
  * 确保文件可以被创建（处理同名文件存在的情况）
  * 
  * @private
  * @param {string} filePath - 原始文件路径
  * @returns {Promise<string>} 可用的文件路径
  */
  async ensureFileCanBeCreated(filePath) {
    const existingFile = this.app.vault.getAbstractFileByPath(filePath);
    if (!existingFile) {
      return filePath;
    }
    const now = new Date();
    const timestamp = now.getTime().toString().slice(-6);
    const pathParts = filePath.split("/");
    const fileName = pathParts[pathParts.length - 1];
    const folderPath = pathParts.slice(0, -1).join("/");
    const nameParts = fileName.split(".");
    const extension = nameParts.length > 1 ? nameParts.pop() : "";
    const baseName = nameParts.join(".");
    const newFileName = `${baseName}_${timestamp}.${extension}`;
    const newFilePath = folderPath ? `${folderPath}/${newFileName}` : newFileName;
    return newFilePath;
  }
  /**
  * 创建笔记文件
  * 
  * @param {string} title - 笔记标题
  * @param {string} content - 笔记内容
  * @returns {Promise<TFile>} 创建的文件对象
  * @throws {Error} 当文件创建失败时抛出错误
  */
  async createNoteFile(title, content) {
    const safeTitle = this.sanitizeFileName(title);
    const fileName = `${safeTitle}.md`;
    const filePath = `${this.settings.bookmarkFolder}/${fileName}`;
    const finalFilePath = await this.ensureFileCanBeCreated(filePath);
    return await this.app.vault.create(finalFilePath, content);
  }
  /**
  * 下载截图
  * 
  * @param {string} url - 网站URL
  * @param {string} noteTitle - 笔记标题
  * @returns {Promise<string>} 截图文件名
  * @throws {Error} 当下载失败时抛出错误
  */
  async downloadScreenshot(url, noteTitle) {
    const screenshotUrl = `https://image.thum.io/get/wait/12/viewportWidth/1600/width/1440/crop/900/png/noanimate/${url}`;
    console.log("Downloading screenshot from:", screenshotUrl);
    try {
      await this.ensureFolderExists(this.settings.attachmentFolder);
      const screenshotFileName = `${this.sanitizeFileName(noteTitle)}.png`;
      const filePath = `${this.settings.attachmentFolder}/${screenshotFileName}`;
      const response = await (0, import_obsidian3.requestUrl)({
        url: screenshotUrl,
        method: "GET",
        headers: {
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
        }
      });
      if (response.status === 200) {
        console.log("Screenshot downloaded successfully");
        await this.app.vault.createBinary(filePath, response.arrayBuffer);
        return screenshotFileName;
      } else {
        throw new Error(`\u622A\u56FE\u4E0B\u8F7D\u5931\u8D25\uFF0C\u72B6\u6001\u7801: ${response.status}`);
      }
    } catch (error) {
      console.error("\u4E0B\u8F7D\u622A\u56FE\u5931\u8D25:", error);
      if (error instanceof Error) {
        throw new Error(`\u65E0\u6CD5\u4E0B\u8F7D\u7F51\u7AD9\u622A\u56FE: ${error.message}`);
      } else {
        throw new Error("\u65E0\u6CD5\u4E0B\u8F7D\u7F51\u7AD9\u622A\u56FE: \u672A\u77E5\u9519\u8BEF");
      }
    }
  }
  /**
   * 构建笔记内容
   * 
   * @param {NoteContentData} data - 笔记数据
   * @returns {string} 生成的笔记内容
   */
  buildNoteContent(data) {
    const frontmatter = {
      created: data.created,
      title: data.title,
      url: data.url,
      description: data.description,
      tags: data.tags
    };
    try {
      return `---
${(0, import_obsidian3.stringifyYaml)(frontmatter)}
---

## \u7F51\u7AD9\u622A\u56FE

screenshot:: ![\u7F51\u7AD9\u622A\u56FE](${this.settings.attachmentFolder}/${encodeURIComponent(data.screenshotFileName)})

## \u7F51\u7AD9\u7B14\u8BB0

${data.bookmarkNote || ""}
`;
    } catch (error) {
      console.error("\u6784\u5EFA\u7B14\u8BB0\u5185\u5BB9\u5931\u8D25:", error);
      throw new Error("\u6784\u5EFA\u7B14\u8BB0\u5185\u5BB9\u65F6\u51FA\u9519");
    }
  }
};

// src/workflow.ts
var _BookmarkWorkflow = class {
  /**
   * 构造函数
   * @param {App} app - Obsidian应用实例
   * @param {BookmarkCreatorSettings} settings - 插件设置
   * @param {BookmarkModal} modal - 模态框实例（可选）
   */
  constructor(app, settings, modal) {
    /** 成功创建的笔记列表 */
    this.createdNotes = [];
    this.app = app;
    this.settings = settings;
    this.modal = modal || new BookmarkModal(app, settings);
    this.aiService = new AiService(settings);
    this.fileManager = new FileManager(app, settings);
    this.instanceId = Math.random().toString(36).substr(2, 9);
    this.createdNotes = [];
  }
  /**
   * 请求取消当前运行的工作流
   * @returns {void}
   */
  requestCancellation() {
    if (_BookmarkWorkflow.isWorkflowRunning && _BookmarkWorkflow.runningInstanceId) {
      _BookmarkWorkflow.isCancellationRequested = true;
      _BookmarkWorkflow.cancellingInstanceId = _BookmarkWorkflow.runningInstanceId;
      console.log(`\u5DE5\u4F5C\u6D41\u53D6\u6D88\u8BF7\u6C42\u5DF2\u53D1\u9001 (\u5B9E\u4F8BID: ${_BookmarkWorkflow.runningInstanceId})`);
    }
  }
  /**
   * 检查是否应该取消当前工作流
   * @returns {boolean} 是否应该取消
   * @private
   */
  shouldCancel() {
    return _BookmarkWorkflow.isCancellationRequested && _BookmarkWorkflow.cancellingInstanceId === this.instanceId;
  }
  /**
   * 重置取消状态
   * @private
   */
  resetCancellationState() {
    _BookmarkWorkflow.isCancellationRequested = false;
    _BookmarkWorkflow.cancellingInstanceId = null;
  }
  /**
   * 启动URL工作流
   * @returns {Promise<boolean>} 是否成功创建所有书签
   */
  async startURLWorkflow() {
    if (_BookmarkWorkflow.isWorkflowRunning) {
      new import_obsidian4.Notice(`\u5DE5\u4F5C\u6D41\u6B63\u5728\u8FD0\u884C\u4E2D (${_BookmarkWorkflow.runningInstanceId})\uFF0C\u8BF7\u7A0D\u5019...`);
      return false;
    }
    _BookmarkWorkflow.isWorkflowRunning = true;
    _BookmarkWorkflow.runningInstanceId = this.instanceId;
    let currentIndex = 0;
    let hasError = false;
    try {
      this.modal.open();
      this.modal.progressMode(true);
      while (currentIndex < waitlist.length) {
        if (this.shouldCancel()) {
          throw new WorkflowCancellationError();
        }
        const item = waitlist.read(currentIndex);
        if (!item) {
          currentIndex++;
          continue;
        }
        try {
          await this.URLWorkflow(item.url, currentIndex);
        } catch (error) {
          console.error(`\u5904\u7406URL\u5931\u8D25: ${item.url}`, error);
          hasError = true;
        }
        currentIndex++;
      }
      waitlist.clear();
      this.modal.setCreatedNotes(this.createdNotes);
      this.modal.setTitle("\u5904\u7406\u5B8C\u6210\uFF01");
      if (!hasError) {
        new import_obsidian4.Notice("\u6240\u6709\u4E66\u7B7E\u521B\u5EFA\u5B8C\u6210\uFF01");
      } else {
        new import_obsidian4.Notice("\u6279\u91CF\u5904\u7406\u5B8C\u6210\uFF0C\u90E8\u5206\u4E66\u7B7E\u521B\u5EFA\u5931\u8D25");
      }
      return !hasError;
    } catch (error) {
      console.error("\u6279\u91CF\u5904\u7406URL\u65F6\u53D1\u751F\u9519\u8BEF:", error);
      if (error instanceof WorkflowCancellationError) {
        new import_obsidian4.Notice("\u5DE5\u4F5C\u6D41\u5DF2\u53D6\u6D88");
      } else {
        new import_obsidian4.Notice("\u6279\u91CF\u5904\u7406\u5931\u8D25: " + (error instanceof Error ? error.message : "\u672A\u77E5\u9519\u8BEF"));
      }
      return false;
    } finally {
      _BookmarkWorkflow.isWorkflowRunning = false;
      _BookmarkWorkflow.runningInstanceId = null;
      this.resetCancellationState();
    }
  }
  /**
   * 执行工作流步骤，统一处理状态更新
   * @param {string} stepId - 步骤ID
   * @param {Function} stepFunction - 步骤执行函数
   * @returns {Promise<any>} 步骤执行结果
   * @private
   */
  async executeStep(stepId, stepFunction) {
    if (this.shouldCancel()) {
      throw new WorkflowCancellationError();
    }
    try {
      waitlist.update(stepId, "processing");
      const result = await stepFunction();
      waitlist.update(stepId, "completed");
      return result;
    } catch (error) {
      waitlist.update(stepId, "failed");
      throw error;
    }
  }
  /**
   * 执行完整的书签创建工作流
   * @param {string} url - 目标网址
   * @param {number} currentIndex - 当前处理索引
   * @returns {Promise<boolean>} 是否成功创建书签
   */
  async URLWorkflow(url, currentIndex) {
    try {
      this.modal.progressMode(true, `\u6B63\u5728\u5904\u7406\u4E2D...${waitlist.length > 1 ? ` (${currentIndex + 1}/${waitlist.length})` : ""} ${new URL(url).hostname}`);
      const webContent = await this.executeStep("get-web-content", async () => {
        return await this.aiService.callApi(url, "jinaReader");
      });
      const searchInfo = await this.executeStep("get-web-rating", async () => {
        return await this.aiService.callApi(url, "jinaSearch");
      });
      const bookmarkYaml = await this.executeStep("generate-bookmark-info", async () => {
        return await this.aiService.callApi(url, "openai", {
          webContent,
          searchInfo
        });
      });
      const noteData = this.parseGeneratedYaml(bookmarkYaml);
      noteData.url = url;
      noteData.screenshotFileName = await this.executeStep("download-web-screenshot", async () => {
        return await this.fileManager.downloadScreenshot(url, noteData.title);
      });
      await this.executeStep("create-bookmark-note", async () => {
        await this.createBookmarkNote(noteData);
      });
      new import_obsidian4.Notice("\u4E66\u7B7E\u521B\u5EFA\u6210\u529F\uFF01");
      return true;
    } catch (error) {
      console.error("\u4E66\u7B7E\u521B\u5EFA\u5DE5\u4F5C\u6D41\u5931\u8D25:", error);
      if (error instanceof Error) {
        new import_obsidian4.Notice(`\u4E66\u7B7E\u521B\u5EFA\u5931\u8D25: ${error.message}`);
      } else {
        new import_obsidian4.Notice("\u4E66\u7B7E\u521B\u5EFA\u5931\u8D25: \u672A\u77E5\u9519\u8BEF");
      }
      return false;
    }
  }
  /**
   * 执行简化的书签创建工作流（仅下载截图和创建笔记）
   * @param {NoteContentData} noteData - 笔记数据
   * @returns {Promise<boolean>} 是否成功创建书签
   */
  async startYAMLWorkflow(yamlContent) {
    if (_BookmarkWorkflow.isWorkflowRunning) {
      new import_obsidian4.Notice(`\u5DE5\u4F5C\u6D41\u6B63\u5728\u8FD0\u884C\u4E2D (${_BookmarkWorkflow.runningInstanceId})\uFF0C\u8BF7\u7A0D\u5019...`);
      return false;
    }
    _BookmarkWorkflow.isWorkflowRunning = true;
    _BookmarkWorkflow.runningInstanceId = this.instanceId;
    try {
      let noteData;
      try {
        noteData = this.parseGeneratedYaml(yamlContent);
      } catch (error) {
        console.error("\u89E3\u6790YAML\u5185\u5BB9\u5931\u8D25:", error);
        new import_obsidian4.Notice("\u89E3\u6790\u4E66\u7B7E\u4FE1\u606F\u5931\u8D25: \u672A\u77E5\u9519\u8BEF");
        return false;
      }
      this.modal.progressMode(false);
      noteData.screenshotFileName = await this.executeStep("download-web-screenshot", async () => {
        return await this.fileManager.downloadScreenshot(noteData.url, noteData.title);
      });
      await this.executeStep("create-bookmark-note", async () => {
        await this.createBookmarkNote(noteData);
      });
      new import_obsidian4.Notice("\u4E66\u7B7E\u521B\u5EFA\u6210\u529F\uFF01");
      return true;
    } catch (error) {
      console.error("\u7B80\u5316\u4E66\u7B7E\u521B\u5EFA\u5DE5\u4F5C\u6D41\u5931\u8D25:", error);
      if (error instanceof WorkflowCancellationError) {
        new import_obsidian4.Notice("\u5DE5\u4F5C\u6D41\u5DF2\u53D6\u6D88");
      } else if (error instanceof Error) {
        new import_obsidian4.Notice(`\u4E66\u7B7E\u521B\u5EFA\u5931\u8D25: ${error.message}`);
      } else {
        new import_obsidian4.Notice("\u4E66\u7B7E\u521B\u5EFA\u5931\u8D25: \u672A\u77E5\u9519\u8BEF");
      }
      return false;
    } finally {
      _BookmarkWorkflow.isWorkflowRunning = false;
      _BookmarkWorkflow.runningInstanceId = null;
      this.resetCancellationState();
    }
  }
  /**
   * 解析AI生成的YAML内容
   * @param {string} yamlContent - YAML内容
   * @returns {NoteContentData} 解析后的笔记数据
   * @private
   */
  parseGeneratedYaml(yamlContent) {
    try {
      let cleanYaml = yamlContent;
      const yamlDelimiter = yamlContent.match(/-{3,}\s*\n([\s\S]*?)\n-{3,}/);
      if (yamlDelimiter) {
        cleanYaml = yamlDelimiter[1].trim();
      } else {
        const yamlCodeBlock = yamlContent.match(/`{3,}ya?ml\s*\n([\s\S]*?)`{3,}/i);
        if (yamlCodeBlock) {
          cleanYaml = yamlCodeBlock[1].trim();
        } else {
          const codeBlock = yamlContent.match(/`{3,}\s*\n([\s\S]*?)`{3,}/);
          if (codeBlock) {
            cleanYaml = codeBlock[1].trim();
          }
        }
      }
      const parsedYaml = (0, import_obsidian4.parseYaml)(cleanYaml);
      if (!parsedYaml.title || !parsedYaml.url) {
        throw new Error("\u4E66\u7B7E\u4FE1\u606F\u4E2D\u7F3A\u5C11\u6807\u9898\u6216URL");
      }
      return {
        created: new Date().toISOString(),
        title: parsedYaml.title,
        url: parsedYaml.url,
        description: parsedYaml.description || "",
        tags: parsedYaml.tags || [],
        screenshotFileName: `${parsedYaml.title}.png`,
        bookmarkNote: parsedYaml.bookmarkNote || ""
      };
    } catch (error) {
      console.error("\u89E3\u6790YAML\u5185\u5BB9\u5931\u8D25:", error);
      throw new Error("\u89E3\u6790\u751F\u6210\u7684\u4E66\u7B7E\u4FE1\u606F\u5931\u8D25");
    }
  }
  /**
   * 创建书签笔记
   * @param {NoteContentData} noteData - 笔记数据
   * @returns {Promise<void>}
   * @private
   */
  async createBookmarkNote(noteData) {
    try {
      const content = this.fileManager.buildNoteContent(noteData);
      const file = await this.fileManager.createNoteFile(noteData.title, content);
      this.createdNotes.push(file.path);
    } catch (error) {
      console.error("\u521B\u5EFA\u7B14\u8BB0\u5931\u8D25:", error);
      throw new Error(`\u521B\u5EFA\u4E66\u7B7E\u7B14\u8BB0\u5931\u8D25: ${error instanceof Error ? error.message : "\u672A\u77E5\u9519\u8BEF"}`);
    }
  }
};
var BookmarkWorkflow = _BookmarkWorkflow;
/** 全局静态锁，跨实例共享 */
BookmarkWorkflow.isWorkflowRunning = false;
/** 当前运行的工作流实例ID */
BookmarkWorkflow.runningInstanceId = null;
/** 全局取消请求标志 */
BookmarkWorkflow.isCancellationRequested = false;
/** 当前请求取消的实例ID */
BookmarkWorkflow.cancellingInstanceId = null;

// src/modal.ts
var BookmarkModal = class extends import_obsidian5.Modal {
  /**
   * 构造函数
   * @param {App} app - Obsidian应用实例
   * @param {any} plugin - 书签创建器插件实例
   */
  constructor(app, plugin) {
    super(app);
    this.modalType = "input";
    /** 当前步骤列表 */
    this.currentSteps = [];
    /** 步骤元素映射，用于快速访问和更新步骤DOM */
    this.stepEls = /* @__PURE__ */ new Map();
    /** 当前运行的进度定时器ID */
    this.currentProgressTimer = null;
    /** 当前正在更新进度的步骤名称 */
    this.currentProcessingStep = null;
    /** waitlist状态更新监听器 */
    this.waitlistUpdateListener = null;
    /** 取消按钮元素 */
    this.cancelButton = null;
    /** 打开所有笔记按钮元素 */
    this.openAllButton = null;
    /** 关闭按钮元素 */
    this.closeButton = null;
    /** 是否正在取消 */
    this.isCancelling = false;
    /** 成功创建的笔记列表 */
    this.createdNotes = [];
    this.plugin = plugin;
    this.workflow = new BookmarkWorkflow(this.app, this.plugin.settings, this);
  }
  /**
  * 模态框打开时的初始化
  * 
  * @returns {void}
  */
  onOpen() {
  }
  /**
   * 切换到输入模式
   * @returns {BookmarkModal} 当前实例，用于链式调用
   */
  inputMode() {
    this.modalType = "input";
    this.contentEl.empty();
    this.setTitle("\u521B\u5EFA\u4E66\u7B7E\u7B14\u8BB0");
    this.createStyle();
    this.createInputArea();
    this.createButtonArea();
    return this;
  }
  /**
   * 切换到进度模式
   * @param full 是否显示完整进度模式
   * @returns {BookmarkModal} 当前实例，用于链式调用
   */
  progressMode(full, title = "\u5904\u7406\u4E2D...") {
    this.modalType = full ? "progress" : "simple-progress";
    this.contentEl.empty();
    this.currentSteps = full ? [...steps.full] : [...steps.simple];
    this.setTitle(title);
    this.createStyle();
    const stepsContainer = this.contentEl.createDiv("bookmark-steps-container");
    this.stepEls.clear();
    this.currentSteps.forEach((step) => {
      const stepEl = stepsContainer.createDiv("bookmark-step");
      stepEl.addClass("step-pending");
      const stepTitle = stepEl.createDiv("step-title");
      stepTitle.textContent = step.title;
      const stepProgress = stepEl.createDiv("step-progress");
      this.stepEls.set(step.name, {
        stepEl,
        stepTitle,
        stepProgress,
        estimatedTime: step.estimatedTime || 10
      });
    });
    const buttonContainer = this.contentEl.createDiv("modal-button-container");
    this.cancelButton = buttonContainer.createEl("button", {
      text: "\u53D6\u6D88",
      cls: "mod-muted"
    });
    this.cancelButton.addEventListener("click", () => this.handleCancel());
    this.openAllButton = buttonContainer.createEl("button", {
      text: "\u6253\u5F00\u6240\u6709\u7B14\u8BB0",
      cls: "mod-cta",
      attr: {
        style: "display: none; margin-right: auto;"
      }
    });
    this.openAllButton.addEventListener("click", () => this.openAllNotes());
    this.closeButton = buttonContainer.createEl("button", {
      text: "\u5173\u95ED",
      cls: "mod-muted",
      attr: {
        style: "display: none;"
      }
    });
    this.closeButton.addEventListener("click", () => this.close());
    this.waitlistUpdateListener = (data) => {
      if (data.step && data.newStatus) {
        this.updateStepStatus(data.step, data.newStatus);
      }
    };
    waitlist.subscribe("update", this.waitlistUpdateListener);
    return this;
  }
  /**
   * 更新步骤状态
   * @param stepName 步骤名称
   * @param status 新的状态
   */
  updateStepStatus(stepName, status) {
    const step = this.stepEls.get(stepName);
    if (!step)
      return;
    const { stepEl, stepTitle, stepProgress, estimatedTime } = step;
    stepEl.removeClass("step-pending");
    stepEl.removeClass("step-processing");
    stepEl.removeClass("step-completed");
    stepEl.removeClass("step-failed");
    stepEl.addClass(`step-${status}`);
    if (status === "processing") {
      if (!stepEl.dataset.startTs)
        stepEl.dataset.startTs = String(Date.now());
      this.startProgressTimer(stepName, stepEl, stepProgress, estimatedTime * 1e3);
    } else {
      stepProgress.textContent = "";
      delete stepEl.dataset.startTs;
      if (this.currentProcessingStep === stepName) {
        this.stopCurrentProgressTimer();
      }
    }
  }
  /**
   * 启动进度定时器
   * @param stepName 步骤名称
   * @param stepEl 步骤元素
   * @param stepProgress 进度百分比元素
   * @param estimatedMsPerStep 预计每个步骤耗时（毫秒）
   */
  startProgressTimer(stepName, stepEl, stepProgress, estimatedMsPerStep) {
    this.stopCurrentProgressTimer();
    this.currentProcessingStep = stepName;
    this.currentProgressTimer = window.setInterval(() => {
      try {
        const startTime = stepEl.dataset.startTs ? Number(stepEl.dataset.startTs) : Date.now();
        const elapsed = Date.now() - startTime;
        const percent = Math.min(99, Math.round(elapsed / estimatedMsPerStep * 100));
        stepProgress.textContent = `${percent}%`;
        if (percent >= 99) {
          this.stopCurrentProgressTimer();
        }
      } catch (error) {
        console.error(`\u6B65\u9AA4 ${stepName} \u8FDB\u5EA6\u66F4\u65B0\u5931\u8D25:`, error);
        this.stopCurrentProgressTimer();
      }
    }, 200);
  }
  /**
   * 停止当前进度定时器
   */
  stopCurrentProgressTimer() {
    if (this.currentProgressTimer !== null) {
      window.clearInterval(this.currentProgressTimer);
      this.currentProgressTimer = null;
      this.currentProcessingStep = null;
    }
  }
  createStyle() {
    const styleEl = this.contentEl.createEl("style");
    if (this.modalType === "input") {
      styleEl.textContent = `
            .bookmark-input-setting {
                flex-direction: column;
                align-items: normal;
            }`;
    }
    if (this.modalType === "progress" || this.modalType === "simple-progress") {
      styleEl.textContent = `
                /* \u6B65\u9AA4\u5BB9\u5668\u6837\u5F0F */
                .bookmark-steps-container {
                    display: flex;
                    flex-direction: column;
                    gap: 10px;
                    width: 100%;
                    padding: 10px 0;
                }
                
                /* \u5355\u4E2A\u6B65\u9AA4\u6837\u5F0F */
                .bookmark-step {
                    display: flex;
                    justify-content: space-between;
                    align-items: center;
                    gap: 4px;
                    padding: 12px;
                    border-radius: 6px;
                    border: 1px solid var(--background-modifier-border);
                    transition: all 0.3s ease;
                }
                
                /* \u6B65\u9AA4\u6807\u9898\u6837\u5F0F */
                .step-title {
                    font-weight: 600;
                    font-size: 14px;
                    color: var(--text-normal);
                    flex: 1;
                }
                
                /* \u6B65\u9AA4\u63CF\u8FF0\u6837\u5F0F */
                .step-desc {
                    font-size: 12px;
                    color: var(--text-muted);
                }
                
                /* \u6B65\u9AA4\u8FDB\u5EA6\u6837\u5F0F */
                .step-progress {
                    color: var(--text-faint);
                    margin-top: 2px;
                    text-align: right;
                    min-width: 40px;
                }
                
                /* \u5F85\u5904\u7406\u72B6\u6001\u6837\u5F0F */
                .step-pending {
                    background-color: var(--background-secondary);
                    border-color: var(--background-modifier-border);
                }
                
                /* \u5904\u7406\u4E2D\u72B6\u6001\u6837\u5F0F */
                .step-processing {
                    background-color: rgba(37, 99, 235, 0.1);
                    border-color: rgba(37, 99, 235, 0.3);
                }
                .step-processing::before {
                    content: '';
                    display: inline-block;
                    width: 16px;
                    height: 16px;
                    margin-right: 8px;
                    border: 2px solid var(--interactive-accent);
                    border-top: 2px solid transparent;
                    border-radius: 50%;
                    animation: spin 1s linear infinite;
                }
                
                /* \u5DF2\u5B8C\u6210\u72B6\u6001\u6837\u5F0F */
                .step-completed {
                    background-color: rgba(16, 185, 129, 0.1);
                    border-color: rgba(16, 185, 129, 0.3);
                }
                .step-completed::before {
                    content: '\u2713';
                    display: inline-block;
                    width: 16px;
                    height: 16px;
                    margin-right: 8px;
                    color: rgb(16, 185, 129);
                    font-weight: bold;
                }
                
                /* \u5931\u8D25\u72B6\u6001\u6837\u5F0F */
                .step-failed {
                    background-color: rgba(239, 68, 68, 0.1);
                    border-color: rgba(239, 68, 68, 0.3);
                }
                .step-failed::before {
                    content: '\u2717';
                    display: inline-block;
                    width: 16px;
                    height: 16px;
                    margin-right: 8px;
                    color: rgb(239, 68, 68);
                    font-weight: bold;
                }
                
                /* \u65CB\u8F6C\u52A8\u753B */
                @keyframes spin {
                    0% { transform: rotate(0deg); }
                    100% { transform: rotate(360deg); }
                }
                
                /* \u6B65\u9AA4\u6807\u9898\u548C\u63CF\u8FF0\u5728\u72B6\u6001\u6837\u5F0F\u4E2D\u7684\u8C03\u6574 */
                .step-processing .step-title,
                .step-completed .step-title,
                .step-failed .step-title {
                    display: flex;
                    align-items: center;
                }
            `;
    }
  }
  /**
  * 创建YAML输入区域
  * @private
  * @returns {void}
  */
  createInputArea() {
    new import_obsidian5.Setting(this.contentEl).setClass("bookmark-input-setting").setName("\u4E66\u7B7E\u4FE1\u606F").setDesc("\u652F\u6301 YAML \u683C\u5F0F\u6216\u76F4\u63A5\u8F93\u5165\u7F51\u5740\u3002YAML \u683C\u5F0F\u5C06\u76F4\u63A5\u5904\u7406\uFF0C\u7F51\u5740\u5C06\u4F7F\u7528 AI \u81EA\u52A8\u751F\u6210\u4E66\u7B7E\u4FE1\u606F").addTextArea((text) => {
      this.mainTextarea = text.inputEl;
      text.setPlaceholder(`\u65B9\u5F0F1 - YAML\u683C\u5F0F\uFF1A
---
created: 
title: \u7F51\u7AD9\u6807\u9898
url: https://example.com/
description: \u7F51\u7AD9\u63CF\u8FF0
tags: 
    - \u6807\u7B7E1
    - \u6807\u7B7E2
---

\u65B9\u5F0F2 - \u76F4\u63A5\u8F93\u5165\u7F51\u5740\uFF1A
https://example.com/`);
      this.mainTextarea.rows = 15;
      this.mainTextarea.style.fontFamily = "monospace";
      this.mainTextarea.style.fontSize = "14px";
      this.mainTextarea.style.width = "100%";
    });
  }
  /**
   * 创建按钮区域
   * @private
   * @returns {void}
   */
  createButtonArea() {
    const buttonContainer = this.contentEl.createDiv("modal-button-container");
    buttonContainer.style.display = "flex";
    buttonContainer.style.gap = "10px";
    buttonContainer.style.marginTop = "20px";
    const createButton = buttonContainer.createEl("button", {
      text: "\u521B\u5EFA\u4E66\u7B7E",
      cls: "mod-cta"
    });
    createButton.addEventListener("click", () => this.startWorkflow());
    const cancelButton = buttonContainer.createEl("button", {
      text: "\u53D6\u6D88",
      cls: "mod-muted"
    });
    cancelButton.addEventListener("click", () => this.close());
  }
  /**
   * 启动书签创建工作流
   * @returns {void}
   */
  startWorkflow() {
    const input = this.mainTextarea.value.trim();
    if (!input) {
      new import_obsidian5.Notice("\u8BF7\u8F93\u5165\u7F51\u5740\u6216\u4E66\u7B7E\u4FE1\u606F");
      return;
    }
    if (/^(-{3,}|`{3,}\w*)$/m.test(input)) {
      this.workflow.startYAMLWorkflow(input.trim());
    } else {
      const lines = input.split("\n").map((l) => l.trim()).filter(Boolean);
      for (const line of lines) {
        try {
          new URL(line);
        } catch (e) {
          new import_obsidian5.Notice(`\u65E0\u6548\u7F51\u5740\uFF1A${line}`);
          return;
        }
      }
      lines.forEach((line) => {
        waitlist.add(line);
      });
      this.workflow.startURLWorkflow();
    }
  }
  /**
  * 模态框关闭时的清理
  * 
  * @returns {void}
  */
  onClose() {
    if (this.waitlistUpdateListener) {
      waitlist.unsubscribe("update", this.waitlistUpdateListener);
      this.waitlistUpdateListener = null;
    }
    this.stopCurrentProgressTimer();
    this.contentEl.empty();
    this.stepEls.clear();
    this.createdNotes = [];
  }
  /**
   * 设置成功创建的笔记列表
   * @param {string[]} notes - 笔记标题列表
   * @returns {void}
   */
  setCreatedNotes(notes) {
    this.createdNotes = notes;
    this.updateButtonStates();
  }
  /**
   * 更新按钮状态
   * @returns {void}
   */
  updateButtonStates() {
    if (this.cancelButton) {
      this.cancelButton.disabled = true;
      this.cancelButton.textContent = "\u5DF2\u5B8C\u6210";
    }
    if (this.openAllButton) {
      this.openAllButton.style.display = this.createdNotes.length > 0 ? "inline-block" : "none";
    }
    if (this.closeButton) {
      this.closeButton.style.display = "inline-block";
    }
  }
  /**
   * 打开所有笔记
   * @returns {Promise<void>}
   */
  async openAllNotes() {
    for (const notePath of this.createdNotes) {
      try {
        const file = this.app.vault.getFileByPath(notePath);
        if (file) {
          await this.app.workspace.getLeaf().openFile(file);
        }
      } catch (error) {
        console.error(`\u6253\u5F00\u7B14\u8BB0\u5931\u8D25: ${notePath}`, error);
      }
    }
    this.close();
  }
  /**
   * 处理取消按钮点击事件
   * @returns {void}
   */
  handleCancel() {
    if (this.isCancelling) {
      return;
    }
    this.isCancelling = true;
    if (this.cancelButton) {
      this.cancelButton.textContent = "\u6B63\u5728\u53D6\u6D88...";
      this.cancelButton.disabled = true;
    }
    this.workflow.requestCancellation();
    new import_obsidian5.Notice("\u6B63\u5728\u53D6\u6D88\u5DE5\u4F5C\u6D41\uFF0C\u8BF7\u7A0D\u5019...");
    setTimeout(() => {
      this.close();
    }, 1e3);
  }
};

// src/main.ts
var BookmarkCreatorPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    /** 插件设置 */
    this.settings = DEFAULT_SETTINGS;
  }
  /**
   * 插件加载时的初始化
   * 设置命令、设置页面等
   * 
   * @async
   * @returns {Promise<void>}
   */
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "create-bookmark",
      name: "\u521B\u5EFA\u4E66\u7B7E\u7B14\u8BB0",
      callback: () => {
        new BookmarkModal(this.app, this).inputMode().open();
      }
    });
    this.registerURI();
    this.addSettingTab(new BookmarkCreatorSettingTab(this.app, this));
    console.log("\u4E66\u7B7E\u521B\u5EFA\u5668\u63D2\u4EF6\u5DF2\u52A0\u8F7D");
  }
  /**
   * 插件卸载时的清理
   * 
   * @returns {void}
   */
  onunload() {
    console.log("\u4E66\u7B7E\u521B\u5EFA\u5668\u63D2\u4EF6\u5DF2\u5378\u8F7D");
  }
  /**
   * 加载插件设置
   * 从存储中读取设置，如果不存在则使用默认设置
   * 
   * @async
   * @returns {Promise<void>}
   */
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  /**
   * 保存插件设置
   * 将当前设置保存到存储中
   * 
   * @async
   * @returns {Promise<void>}
   */
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * 注册URI处理
   * 允许通过URI创建书签笔记
   * 
   * @returns {void}
   */
  registerURI() {
    this.registerObsidianProtocolHandler("bookmark", async (param) => {
      if (param && param.add) {
        try {
          new URL(param.add);
          waitlist.add(param.add);
          new BookmarkWorkflow(this.app, this.settings).startURLWorkflow();
        } catch (error) {
          new import_obsidian6.Notice("\u521B\u5EFA\u4E66\u7B7E\u5931\u8D25\uFF0CURL\u683C\u5F0F\u9519\u8BEF");
        }
      }
    });
  }
};
