/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BookmarkCreatorPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  bookmarkFolder: "Bookmarks",
  attachmentFolder: "assets/images"
};
var BookmarkCreatorPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "create-bookmark",
      name: "\u521B\u5EFA\u4E66\u7B7E\u7B14\u8BB0",
      callback: () => {
        new BookmarkModal(this.app, this).open();
      }
    });
    this.addSettingTab(new BookmarkCreatorSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * 确保文件夹存在
   */
  async ensureFolderExists(folderPath) {
    const folder = this.app.vault.getAbstractFileByPath(folderPath);
    if (!folder) {
      await this.app.vault.createFolder(folderPath);
    }
  }
  /**
   * 清理文件名，移除非法字符
   */
  sanitizeFileName(fileName) {
    return fileName.replace(/[<>:\"/\\|?*]/g, "_").replace(/\s+/g, " ").trim();
  }
  /**
   * 下载截图
   */
  async downloadScreenshot(url, filePath) {
    console.log("Downloading screenshot from:", url);
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url,
        method: "GET",
        headers: {
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
        }
      });
      if (response.status === 200) {
        await this.app.vault.createBinary(filePath, response.arrayBuffer);
      } else {
        throw new Error(`\u622A\u56FE\u4E0B\u8F7D\u5931\u8D25\uFF0C\u72B6\u6001\u7801: ${response.status}`);
      }
    } catch (error) {
      console.error("\u4E0B\u8F7D\u622A\u56FE\u5931\u8D25:", error);
      throw new Error(`\u65E0\u6CD5\u4E0B\u8F7D\u7F51\u7AD9\u622A\u56FE: ${error.message}`);
    }
  }
  /**
   * 从YAML数据创建书签笔记
   */
  async createBookmarkNoteFromYaml(yamlData) {
    try {
      await this.ensureFolderExists(this.settings.bookmarkFolder);
      await this.ensureFolderExists(this.settings.attachmentFolder);
      let title = yamlData.title || "";
      const url = yamlData.url || "";
      const description = yamlData.description || "";
      const tags = yamlData.tags || [];
      const created = yamlData.created || new Date().toLocaleString("zh-CN").replace(/\//g, "-");
      if (!title) {
        throw new Error("\u6807\u9898\u4E0D\u80FD\u4E3A\u7A7A");
      }
      if (!url) {
        throw new Error("URL\u4E0D\u80FD\u4E3A\u7A7A");
      }
      try {
        new URL(url);
      } catch (e) {
        throw new Error("URL\u683C\u5F0F\u65E0\u6548");
      }
      const safeTitle = this.sanitizeFileName(title);
      const fileName = `${safeTitle}.md`;
      const filePath = `${this.settings.bookmarkFolder}/${fileName}`;
      const screenshotUrl = `https://image.thum.io/get/wait/12/viewportWidth/1600/width/1440/crop/900/png/noanimate/${url}`;
      const screenshotFileName = `${safeTitle}.png`;
      const screenshotPath = `${this.settings.attachmentFolder}/${screenshotFileName}`;
      await this.downloadScreenshot(screenshotUrl, screenshotPath);
      const noteContent = this.buildNoteContentFromYaml({
        created,
        title,
        url,
        description,
        tags,
        screenshotFileName
      });
      const file = await this.app.vault.create(filePath, noteContent);
      await this.app.workspace.getLeaf().openFile(file);
      new import_obsidian.Notice(`\u4E66\u7B7E\u7B14\u8BB0 "${title}" \u521B\u5EFA\u6210\u529F\uFF01`);
    } catch (error) {
      console.error("\u521B\u5EFA\u4E66\u7B7E\u7B14\u8BB0\u5931\u8D25:", error);
      new import_obsidian.Notice(`\u521B\u5EFA\u4E66\u7B7E\u7B14\u8BB0\u5931\u8D25: ${error.message}`);
    }
  }
  /**
   * 从YAML数据构建笔记内容
   */
  buildNoteContentFromYaml(data) {
    const tagsString = data.tags.length > 0 ? data.tags.join(", ") : "";
    const screenshotLink = `screenshot:: ![\u7F51\u7AD9\u622A\u56FE](${this.settings.attachmentFolder}/${data.screenshotFileName})`;
    return `---
created: ${data.created}
title: "${data.title}"
url: "${data.url}"
description: "${data.description}"
tags: [${tagsString}]
---

## \u7F51\u7AD9\u622A\u56FE

${screenshotLink}

## \u7F51\u7AD9\u7B14\u8BB0

`;
  }
};
var BookmarkModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u521B\u5EFA\u4E66\u7B7E\u7B14\u8BB0" });
    new import_obsidian.Setting(contentEl).setName("\u4E66\u7B7E\u4FE1\u606F").setDesc("\u8BF7\u6309YAML\u683C\u5F0F\u8F93\u5165\u4E66\u7B7E\u4FE1\u606F").addTextArea((text) => {
      this.yamlTextarea = text.inputEl;
      text.setPlaceholder(`---
created: 
title: \u7F51\u7AD9\u6807\u9898
url: https://example.com/
description: \u7F51\u7AD9\u63CF\u8FF0
tags: 
    - \u6807\u7B7E1
    - \u6807\u7B7E2
---`);
      this.yamlTextarea.rows = 15;
      this.yamlTextarea.style.fontFamily = "monospace";
      this.yamlTextarea.style.fontSize = "14px";
    });
    const buttonContainer = contentEl.createDiv("modal-button-container");
    buttonContainer.style.display = "flex";
    buttonContainer.style.gap = "10px";
    buttonContainer.style.marginTop = "20px";
    const createButton = buttonContainer.createEl("button", {
      text: "\u521B\u5EFA\u4E66\u7B7E",
      cls: "mod-cta"
    });
    createButton.addEventListener("click", () => this.createBookmark());
    const cancelButton = buttonContainer.createEl("button", {
      text: "\u53D6\u6D88",
      cls: "mod-muted"
    });
    cancelButton.addEventListener("click", () => this.close());
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
  /**
   * 解析YAML内容
   */
  parseYamlContent(yamlText) {
    try {
      const yamlMatch = yamlText.match(/---\s*\n([\s\S]*?)\n---/);
      if (!yamlMatch) {
        throw new Error("\u672A\u627E\u5230YAML\u683C\u5F0F\u5185\u5BB9");
      }
      const yamlContent = yamlMatch[1];
      const result = {};
      const lines = yamlContent.split("\n");
      let currentKey = "";
      let currentValue = "";
      let inTags = false;
      const tags = [];
      for (const line of lines) {
        const trimmedLine = line.trim();
        if (trimmedLine.startsWith("tags:")) {
          inTags = true;
          currentKey = "tags";
          continue;
        }
        if (inTags) {
          if (trimmedLine.startsWith("- ")) {
            tags.push(trimmedLine.substring(2).trim());
          } else if (trimmedLine && !trimmedLine.startsWith("-")) {
            inTags = false;
          }
          continue;
        }
        const colonIndex = trimmedLine.indexOf(":");
        if (colonIndex > 0) {
          currentKey = trimmedLine.substring(0, colonIndex).trim();
          currentValue = trimmedLine.substring(colonIndex + 1).trim();
          if (currentValue) {
            result[currentKey] = currentValue;
          }
        }
      }
      if (tags.length > 0) {
        result.tags = tags;
      }
      return result;
    } catch (error) {
      throw new Error(`YAML\u89E3\u6790\u5931\u8D25: ${error.message}`);
    }
  }
  /**
   * 创建书签
   */
  async createBookmark() {
    const yamlText = this.yamlTextarea.value.trim();
    if (!yamlText) {
      new import_obsidian.Notice("\u8BF7\u8F93\u5165\u4E66\u7B7E\u4FE1\u606F");
      return;
    }
    try {
      const parsedData = this.parseYamlContent(yamlText);
      const title = parsedData.title;
      const url = parsedData.url;
      if (!title) {
        new import_obsidian.Notice("\u8BF7\u8F93\u5165\u6807\u9898");
        return;
      }
      if (!url) {
        new import_obsidian.Notice("\u8BF7\u8F93\u5165\u7F51\u5740");
        return;
      }
      try {
        new URL(url);
      } catch (e) {
        new import_obsidian.Notice("\u8BF7\u8F93\u5165\u6709\u6548\u7684\u7F51\u5740");
        return;
      }
      this.close();
      await this.plugin.createBookmarkNoteFromYaml(parsedData);
    } catch (error) {
      new import_obsidian.Notice(`\u8F93\u5165\u683C\u5F0F\u9519\u8BEF: ${error.message}`);
    }
  }
};
var BookmarkCreatorSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u4E66\u7B7E\u521B\u5EFA\u5668\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u4E66\u7B7E\u6587\u4EF6\u5939").setDesc("\u5B58\u50A8\u4E66\u7B7E\u7B14\u8BB0\u7684\u6587\u4EF6\u5939\u8DEF\u5F84").addText((text) => text.setPlaceholder("Bookmarks").setValue(this.plugin.settings.bookmarkFolder).onChange(async (value) => {
      this.plugin.settings.bookmarkFolder = value.trim() || "Bookmarks";
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u9644\u4EF6\u6587\u4EF6\u5939").setDesc("\u5B58\u50A8\u622A\u56FE\u7684\u6587\u4EF6\u5939\u8DEF\u5F84").addText((text) => text.setPlaceholder("Attachments").setValue(this.plugin.settings.attachmentFolder).onChange(async (value) => {
      this.plugin.settings.attachmentFolder = value.trim() || "Attachments";
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "\u4F7F\u7528\u8BF4\u660E" });
    containerEl.createEl("p", {
      text: '1. \u4F7F\u7528\u547D\u4EE4\u9762\u677F (Ctrl/Cmd + P) \u8F93\u5165 "\u521B\u5EFA\u4E66\u7B7E\u7B14\u8BB0" \u6765\u542F\u52A8\u63D2\u4EF6'
    });
    containerEl.createEl("p", {
      text: "2. \u6309YAML\u683C\u5F0F\u8F93\u5165\u4E66\u7B7E\u4FE1\u606F"
    });
    containerEl.createEl("p", {
      text: "3. \u63D2\u4EF6\u4F1A\u81EA\u52A8\u8865\u5168\u521B\u5EFA\u65F6\u95F4\u3001\u751F\u6210\u7F51\u7AD9\u622A\u56FE\u5E76\u521B\u5EFA\u7B14\u8BB0"
    });
    containerEl.createEl("p", {
      text: "4. \u622A\u56FE\u53EF\u80FD\u9700\u8981\u51E0\u79D2\u949F\u65F6\u95F4\u751F\u6210\uFF0C\u8BF7\u8010\u5FC3\u7B49\u5F85"
    });
    containerEl.createEl("h4", { text: "YAML\u683C\u5F0F\u793A\u4F8B\uFF1A" });
    const exampleCode = containerEl.createEl("pre", {
      text: `---
created: 
title: \u5C0F\u4F17\u8F6F\u4EF6
url: https://www.appinn.com/
description: \u4E13\u6CE8\u5206\u4EAB\u514D\u8D39\u3001\u5C0F\u5DE7\u3001\u5B9E\u7528\u3001\u6709\u8DA3\u3001\u7EFF\u8272\u8F6F\u4EF6\u4E0E\u5E94\u7528\u7684\u56E2\u961F\u535A\u5BA2
tags: 
    - \u79D1\u6280\u6570\u7801/\u8F6F\u4EF6\u4E0B\u8F7D
    - \u5B9E\u7528\u5DE5\u5177
    - \u8F6F\u4EF6\u8BC4\u6D4B
---`,
      cls: "yaml-example"
    });
    exampleCode.style.backgroundColor = "#f5f5f5";
    exampleCode.style.padding = "10px";
    exampleCode.style.borderRadius = "4px";
    exampleCode.style.fontFamily = "monospace";
    exampleCode.style.fontSize = "14px";
    exampleCode.style.overflowX = "auto";
  }
};
